# Site settings
title: "Resume: Brian J. Stankiewicz"
description: "Brian J. Stankiewicz on-line resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Brian J. Stankiewicz, Ph.D."
resume_title:                   "3M Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "brian@stankiewiczfamily.org"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "612-306-5432"
resume_contact_address:         "St. Paul, MN"

resume_header_contact_info:     "St. Paul, MN • 612-306-5432 • bstankie@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a builder of products, technology, teams and capabilities. Technology is continuously evolving and to fully leverage the evoloution it requires a clear vision, strong leadership and unrelenting courage to transform a potential opportunity into reality. It requires getting the best out of everyone by creating a safe environment where team members can safely suggest and disagree with potential solutions to come to the best possible solution. However, when a clear decision is made, everyone is commited to making that decision successful. Successful transformation requires influencing an orgaization at the macro level through vision and opportunity while simultaneously coaching the technical teams at the individual level. I can write code on a project and then turn around and present a long-term technical vision with a business and technology roadmap to executives. I know how to attract the best minds from universities and develop long-term relationships with professors to build a high-quality hiring pipeline and I have coached and developed existing talent within an organization to help transform an organization's capabilities.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bstankie/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/brianstankiewicz/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://www.bstankie.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
