# Site settings
title: "Resume: Brian J. Stankiewicz"
description: "Brian J. Stankiewicz on-line resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Brian J. Stankiewicz, Ph.D."
resume_title:                   "Data Scientist: Tech. Evangelist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "bstankie@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "612-306-5432"
resume_contact_address:         "St. Paul, MN"

resume_header_contact_info:     "St. Paul, MN • 612-306-5432 • bstankie@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>My passion is turning potential technical opportunities into reality. I am a builder of products, technology, teams and capabilities. I can write code, discuss technical solutions with engineers and then turn around and present a long-term business and technology roadmap to executives and technical teams. Some of these efforts have led new commercial 'bit-based' opportunities in an 'atom-based' fortune 500 company. In the process I have had the priviledge of serving as a 'bit-based technology mentor' to executives and simultaneously had the honor to serve as a coach for talented engineers who wanted to expand their skills in machine learning, data science and/or software engineering. I have an insatiable curiosity, relentless courage, and exercise servent leadership by practicing (and evangalizing) the 'Disagree and Commit' philosophy. These efforts are never done alone, so finding, attracting and unleashing the brightest minds on problems is vital for near-term execution and long-term sustainability. I have been most successful in attracting these minds when they understand the root problem and that finding the solutions is 'worthy of their time'. But just as important, these bright minds need to know that they can influence the direction and scope of the project.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bstankie/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/brianstankiewicz/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://www.bstankie.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
