# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Brian J. Stankiewicz"
resume_title:                   "3M Data Scientist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "brian@stankiewiczfamily.org"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "612-306-5432"
resume_contact_address:         "St. Paul, MN"

resume_header_contact_info:     "St. Paul, MN • 612-306-5432 • brian@stankiewiczfamily.org"
display_header_contact_info:    "false"

resume_header_intro: "<p>The teams I lead solve hard, valuable and  impactful technical problems by leveraging data and artificial intelligence. These problems typically start on the ‘fuzzy front end’ in which the path from ‘here to success’ is often not immediately apparent. Working with the teams we work to  simplify the problem to the key questions that need to be answered and/or the biggest risk items and drive the research and development at those items. This has lead to multiple products or a deep understanding of why the goal is currently unobtainable.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bstankie/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/brianstankiewicz/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://BrianStankiewicz.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
